### ISSUE TITLE
Can't load data into geneSLOPE

### ISSUE THREAD

**Issue by signor-molevol** [psobczyk/geneSLOPE#2]
Hi,

I have a normal .ped and .map file generated by vcftools using the --plink command. As directed by the manual I convert the .ped file to a .raw file using the following command:

./plink --file 2_test --recodeAD --out 2_test

phenotype<-read_phenotype(file="phenotypes3.txt")

screening.result<-screen_snps("2_test.raw", mapFile="2_test.map", phenotype, chunkSize=10, verbose=FALSE) 

But I consistently get this this error: 

Error in screen_snps("2_test.raw"
Number of SNPs from .map and .raw data do not match

The vcf file is fine, the ped and map files are fine, and I don't understand what the issue is.

The issue is these are automatically generated files with no problems, so its not as simple as figuring that my map and snp files are really of a different length.

**Comment by signor-molevol** [comment]
Ok, the manual is wrong and doesn't provide sufficient detail. 

Its --recodeA not --recodeAD, and then you need to make sure that your headers are in quotes which is not a default output for plink.

 Also the phenotype file needs to have your genotype and family names in quotes.

**Comment by psobczyk** [comment]
I'm glad that you managed to solve your problem. I will look into it and update vignette soon.

If you have any other problem, please let me know.

**Comment by signor-molevol** [comment]
Yes, actually, the example map file you provide is nonstandard for plink. Could you describe the columns? Plink output is generally like this: 

1	1:3169	0	3169
1	1:3204	0	3204
1	1:5096	0	5096
1	1:5992	0	5992
1	1:7109	0	7109
1	1:10035	0	10035
1	1:10152	0	10152
1	1:10461	0	10461

And your example file is like this:

18	"rs6508028"	46.4941	46494085
4	"rs4697406"	23.3423	23342299
17	"rs7209023"	63.349	63348972
16	"rs7195630"	22.7994	22799350
18	"rs8096910"	48.0397	48039732
2	"rs11688203"	126.902	126902407
6	"rs7381972"	57.3013	57301325
9	"rs4741946"	4.29139	4291392
8	"rs11785244"	23.7882	23788195
1	"rs7527450"	87.4219	87421940
13	"rs9557025"	98.1208	98120753
4	"rs10001607"	56.0441	56044127
17	"rs7221133"	51.745	51744950
6	"rs605107"	10.5864	10586428

**Comment by psobczyk** [comment]
It seems to me that map file format is in accordance with PLINK. See: https://www.cog-genomics.org/plink2/formats#map 

I believe that .fam is also ok: https://www.cog-genomics.org/plink2/formats#fam

There are indeed no sample names in .raw. Those are assumed to be in the same order as .fam

**Comment by signor-molevol** [comment]
--recodeA will not work if the sample names are zeroed out in the .ped file.

Anyway, it just seems like the manual could use some correcting/specifics.

Thanks for the attention!

**Comment by signor-molevol** [comment]
Another question: I find one 'clump representative' that is significant, but when I try to identify it using the described plot(slope.result) I get this error: 

Error in plot.data$snp[plot.data$chromosome == i] <- granice$x[i] + plot.data$snp[plot.data$chromosome ==  : 
  replacement has length zero

Perhaps this is because I am only analyzing a single chromosome?

**Comment by psobczyk** [comment]
This could be a reason, but I need to debug to be sure and, hopefully, fix the problem. Let me check it and get back to you tomorrow on that.

**Comment by psobczyk** [comment]
@signor-molevol I was not able to reproduce your issue. I can try again if you provide some sample of your data

**Comment by signor-molevol** [comment]
Can I have your email?

**Comment by psobczyk** [comment]
You can find it in Descriptio file in the repository. Sorry, but I don't want to post it online :)
